# 主题设置定义文件，配置主题的设置项表单。详细文档请查阅 设置选项。https://docs.halo.run/developer-guide/theme/settings/
apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-starter-setting
spec:
  forms:
    - group: style
      label: 样式
      formSchema:
        - $formkit: color
          name: background_color
          label: 背景颜色
          value: "#f2f2f2"
